export const AppConstant = {
  SESSION_STORAGE_USER_KEY: 'SESSION_STORAGE_USER',
  SESSION_STORAGE_TOKEN_KEY: 'SESSION_STORAGE_TOKEN_KEY',
  CART_ITEMS_KEY: 'CART_ITEMS_KEY',
  BOOK_CATEGORIES: ['drama', 'comedy', 'sport'],
  BOOK_LIST_VIEW: 'BOOK_LIST_VIEW',
  BOOK_DETAIL_VIEW: 'BOOK_DETAIL_VIEW'
};
